[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_end = "QWtuDBJZXhvPJx6JKNSA5bY998s1cfxE8C6wYgVH5bn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = '~\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
