# Generated by Django 5.1.3 on 2024-11-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_student_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="file",
        ),
        migrations.RemoveField(
            model_name="student",
            name="image",
        ),
    ]
