create_content_task:
  description: >
    Generate an engaging LinkedIn post focused on relevant industry topics and trending hashtags.
  expected_output: >
    A LinkedIn post draft, optimized for maximum engagement.

engage_audience_task:
  description: >
    Engage with LinkedIn followers by liking and commenting on relevant posts and responding to comments on recent posts.
  expected_output: >
    A summary of all engagement activities completed, including any new followers or connections.

analyze_growth_task:
  description: >
    Analyze engagement metrics, such as views, likes, and follower growth, and save insights to Weaviate.
  expected_output: >
    A detailed report on LinkedIn engagement performance with actionable recommendations.
